uoLoginUrl = 'https://login.microsoftonline.com/'
uoBookRoomUrl = 'https://bibliorooms.uottawa.ca/'

boundBoxPixelOffset = 40

FIRST_HALF_INDICATOR = 'FIRST-HALF-FREE'
SECOND_HALF_INDICATOR = 'SECOND-HALF-FREE'
FULLY_RESERVABLE_INDICATOR = 'FREE'
FULLY_BOOK_INDICATOR = 'FULL'
CLOSED_INDICATOR = 'CLOSE'

FIRST_HALF_FULL_SECOND_HALF_CLOSE_INDICATOR = 'FIRST-HALF_FULL_SECOND_HALF_CLOSE'
FIRST_HALF_FREE_SECOND_HALF_CLOSE_INDICATOR = 'FIRST-HALF_FREE_SECOND_HALF_CLOSE'

FIRST_HALF_CLOSE_SECOND_HALF_FULL_INDICATOR = 'FIRST-HALF_FREE_SECOND_HALF_FULL'
FIRST_HALF_CLOSE_SECOND_HALF_FREE_INDICATOR = 'FIRST-HALF_CLOSE_SECOND_HALF_FREE'

PORTION_HEIGHT_DIVISOR = 2
PORTION_WIDTH_DIVISOR = 2

PORTION_HEIGHT_CORRECTOR = 2
PORTION_WIDTH_CORRECTOR = 2

NARROW_SEARCH_MAX_ITERATION = 3

CLOSE_IMAGE_RED_VALUE = 207
CLOSE_IMAGE_GREEN_VALUE = 157
CLOSE_IMAGE_BLUE_VALUE = 155