uoLoginUrl = 'https://login.microsoftonline.com/'
uoBookRoomUrl = 'https://bibliorooms.uottawa.ca/'

boundBoxPixelOffset = 40

FIRST_HALF_INDICATOR = 'FIRST-HALF-FREE'
SECOND_HALF_INDICATOR = 'SECOND-HALF-FREE'
FULLY_RESERVABLE_INDICATOR = 'FREE'
FULLY_BOOK_INDICATOR = 'FULL'
CLOSED_INDICATOR = 'CLOSE'

FIRST_HALF_FULL_SECOND_HALF_CLOSE_INDICATOR = 'FIRST_HALF_FULL_SECOND_HALF_CLOSE'
FIRST_HALF_FREE_SECOND_HALF_CLOSE_INDICATOR = 'FIRST_HALF_FREE_SECOND_HALF_CLOSE'

FIRST_HALF_CLOSE_SECOND_HALF_FULL_INDICATOR = 'FIRST_HALF_FREE_SECOND_HALF_FULL'
FIRST_HALF_CLOSE_SECOND_HALF_FREE_INDICATOR = 'FIRST_HALF_CLOSE_SECOND_HALF_FREE'

TEXT_FREE = 'FREE'
TEXT_FULL = 'FULL'
TEXT_FIRST_HALF = 'Ffree'
TEXT_SECOND_HALF = 'Sfree'
TEXT_CLOSE = 'CLOS'
TEXT_FIRST_HALF_FREE_SECOND_HALF_CLOSE = 'FHfSC'
TEXT_FIRST_HALF_FULL_SECOND_HALF_CLOSE = 'FFSC'
TEXT_FIRST_HALF_CLOSE_SECOND_HALF_FREE = 'FCSf'
TEXT_FIRST_HALF_CLOSE_SECOND_HALF_FULL = 'FCSF'
TEXT_UNDEFINED = 'UND'


PORTION_HEIGHT_DIVISOR = 2
PORTION_WIDTH_DIVISOR = 2

PORTION_HEIGHT_CORRECTOR = 2
PORTION_WIDTH_CORRECTOR = 2

NARROW_SEARCH_MAX_ITERATION = 3

CLOSE_IMAGE_RED_MAX_VALUE = 220
CLOSE_IMAGE_RED_MIN_VALUE = 120

CLOSE_IMAGE_GREEN_MAX_VALUE = 200
CLOSE_IMAGE_GREEN_MIN_VALUE = 110

CLOSE_IMAGE_BLUE_MAX_VALUE = 200
CLOSE_IMAGE_BLUE_MIN_VALUE = 110